workflows:
  msr-android:
    name: MSRBrowser Build
    max_build_duration: 60
    environment:
       vars:
             JAVE_VERSION: 17
    android: 
        image:latest
    scripts:
       - name: Build APK
          script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
