workflows:
  android-workflow:
    name: Build MSRBrowser APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      android:
        image: latest
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
